project:
  type: book

book:
  title: "The {TEEMS} R package user manual"
  author: "Matthew Cantele"
  site-url: https://teemsphere.github.io/
  repo-url: https://github.com/teemsphere/teemsphere.github.io
  repo-branch: main
  repo-actions: [edit]
  #sharing: [linkedin]
  #page-footer: "How to get help: <https://books.ropensci.org/targets/help.html><br>Copyright 2025, Eli Lilly and Company" 
  chapters:
    - introduction.qmd
    - part: "Getting started"
      chapters:
        - dependencies.qmd
    #    - getting_started.qmd
    #    - overview.qmd
    #     - help.qmd
    #     - debugging.qmd
    - part: "Data inputs"
      chapters:
        - data_load.qmd
      #  - tab_file.qmd
      #   - part: "Input data"
  #     chapters:
  #       - crew.qmd
  #       - performance.qmd
    - part: "Models"
    - part: "Closures"
    - part: "Shocks"
     # chapters:
        # - uniform_shocks.qmd
        # - custom_shocks.qmd
        # - scenario_shocks.qmd
    - part: "Deploying and solving the model"
        # - aux_dat.qmd
        # - data_mod.qmd
  #   - part: "Solving the model"
  #     chapters:
  #       - dynamic.qmd
  #       - static.qmd
  # appendices:
  #   - hpc.qmd
  #   - drake.qmd
  #   - markdown.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
