project:
  type: book

book:
  title: "The {TEEMS} R package user manual"
  author: "Matthew Cantele"
  site-url: https://teems-org.github.io/
  repo-url: https://github.com/teems-org/teems-org/
  repo-branch: main
  repo-actions: [edit]
  #sharing: [linkedin]
  #page-footer: "How to get help: <https://books.ropensci.org/targets/help.html><br>Copyright 2025, Eli Lilly and Company" 
  chapters:
    - index.qmd
    - part: "{teems} installation"
      chapters:
    #    - dependencies.qmd
    #    - getting_started.qmd
    #    - overview.qmd
    #     - help.qmd
    #     - debugging.qmd
    - part: "General model specifications"
      chapters:
        - tab_file.qmd
      #   - part: "Input data"
  #     chapters:
  #       - crew.qmd
  #       - performance.qmd
    - part: "Shocks and closures"
      chapters:
        - closures.qmd
        - shocks.qmd
        - primary_dat.qmd
        - aux_dat.qmd
        - data_mod.qmd
  #   - part: "Solving the model"
  #     chapters:
  #       - dynamic.qmd
  #       - static.qmd
  # appendices:
  #   - hpc.qmd
  #   - drake.qmd
  #   - markdown.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
