# Deploying the model

## Overview

`ems_deploy()` consolidates all user inputs and carries out all operations necessary to run a CGE model.
It accumulates and validates data and model inputs, processes shocks and closure swaps, and writes all required input files to disk.
The output file path serves as a required input to [`ems_solve()`](solve.qmd).

## Arguments

| Argument | Default | Description |
|----------|---------|-------------|
| `.data` | | A list of data.tables generated by [`ems_data()`](data_load.qmd) |
| `model` | | A tibble generated by [`ems_model()`](model_load.qmd) |
| `shock` | `NULL` | A shock object or list of shock objects produced by [`ems_uniform_shock()`](uniform_shocks.qmd), [`ems_custom_shock()`](custom_shocks.qmd), or [`ems_scenario_shock()`](scenario_shocks.qmd). When `NULL`, a null shock is carried out which effectively returns base data |
| `swap_in` | `NULL` | Character vector, [`ems_swap()`](swaps.qmd) object, or a list of any combination. Variables to be made exogenous |
| `swap_out` | `NULL` | Character vector, [`ems_swap()`](swaps.qmd) object, or a list of any combination. Variables to be made endogenous |
| `write_dir` | `tools::R_user_dir("teems", "cache")` | Base directory where the "teems" subdirectory will be created for input files and model solution |
| `shock_file` | `NULL` | Path to a `.shf` shock file. No checks or modifications will be conducted on this file |

## Basic usage

The simplest deployment requires only data and model inputs.
With no shock supplied, a null shock is carried out:
```r
cmf_path <- ems_deploy(
  .data = dat,
  model = model
)
```

## Deploying with shocks and swaps

A single shock can be passed directly:
```r
shock <- ems_uniform_shock(var = "pop", value = 1)

cmf_path <- ems_deploy(
  .data = dat,
  model = model,
  shock = shock
)
```

Multiple shocks are combined in a list:
```r
pop_shk <- ems_uniform_shock(var = "pop", value = 1)
aoall_shk <- ems_custom_shock(var = "aoall", input = aoall_df)

cmf_path <- ems_deploy(
  .data = dat,
  model = model,
  shock = list(pop_shk, aoall_shk)
)
```

## Closure swaps

A single full variable swap swaps one variable in and one out using plain strings:
```r
shock <- ems_uniform_shock(var = "qfd", value = 1)

cmf_path <- ems_deploy(
  .data    = dat,
  model    = model,
  shock    = shock,
  swap_in  = "qfd",
  swap_out = "tfd"
)
```

Multiple full variable swaps are passed as character vectors.
Partial swaps use [`ems_swap()`](swaps.qmd) objects and can be mixed with strings in a list:
```r
# Multiple full variable swaps
cmf_path <- ems_deploy(
  .data    = dat,
  model    = model,
  shock    = shock,
  swap_in  = c("qfd", "yp"),
  swap_out = c("tfd", "dppriv")
)

# Mixed partial and full swaps
yp_row     <- ems_swap("yp",     REGr = "row")
dppriv_row <- ems_swap("dppriv", REGr = "row")

cmf_path <- ems_deploy(
  .data = dat,
  model = model,
  shock = shock,
  swap_in  = list(yp_row, "qfd"),
  swap_out = list(dppriv_row, "tfd")
)
```

## User-generated inputs
`ems_deploy()` allows for user-generated shock files via the `shock_file` argument.
In the case of shock files, no checks or operations will be conducted (i.e., the shock file as loaded is considered the final input).
User-supplied closure files will however be processed if swaps are supplied.

## Persistent files
Good practice in R dictates that a user's machine state is not modified.
In order to comply with this guidance, [`teems`](https://github.com/teemsphere/teems-R) will only write to temporary folders associated with the [`teems`](https://github.com/teemsphere/teems-R) package (output of `tools::R_user_dir("teems", "cache")`) and these files will be removed upon loading an new R session.
If persistent data is desired, users must provide a path to a local directory via `write_dir`:
```r
cmf_path <- ems_deploy(
  .data = dat,
  model = model,
  shock = shock,
  write_dir = "~/my_project/output"
)
```
